name: test

on: [push]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Setup Lua
      uses: mah0x211/setup-lua@v1
    -
      name: Install Tools
      run: luarocks install luacheck
    -
      name: Run luacheck
      run: |
        luacheck .
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lua-version:
          - "5.1"
          - "5.2"
          - "5.3"
          - "5.4"
          - "lj-v2.1"
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    -
      name: Setup Lua ${{ matrix.lua-version }}
      uses: mah0x211/setup-lua@v1
      with:
        lua-version: ${{ matrix.lua-version }}
    -
      name: Install
      run: |
        luarocks make OPENDIR_COVERAGE=1
    -
      name: Install Tools
      run: |
        sudo apt install lcov -y
        luarocks install assert
    -
      name: Run Test
      run: |
        lua ./test/opendir_test.lua
    -
      name: Generate coverage reports
      run: |
        sh ./covgen.sh
    -
      name: Upload c coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/lcov.info
        flags: unittests

